In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Q1

In [4]:
print('Numpy Version= '+np.__version__)

Numpy Version= 1.19.5


## Q2

In [5]:
print('Pandas Version= '+pd.__version__)

Pandas Version= 1.3.2


In [59]:
df = pd.read_csv(r'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv')

## Optional Part

In [60]:
df.columns = df.columns.str.lower().str.replace(" ","_")


In [61]:
df.columns

Index(['make', 'model', 'year', 'engine_fuel_type', 'engine_hp',
       'engine_cylinders', 'transmission_type', 'driven_wheels',
       'number_of_doors', 'market_category', 'vehicle_size', 'vehicle_style',
       'highway_mpg', 'city_mpg', 'popularity', 'msrp'],
      dtype='object')

In [62]:
df[df['make']=='BMW'].msrp.mean()

61546.76347305389

In [63]:
df[df.year >= 2015].engine_hp.isnull().sum()

51

In [65]:
mean_hp_before = df['engine_hp'].mean()

In [57]:
df['engine_hp'] = df['engine_hp'].fillna(df['engine_hp'].mean())

In [66]:
mean_hp_after = df.engine_hp.mean()

## q5

nothing changed because filling the empty values with the mean values, won't effect the total mean of engine_hp

In [67]:
print(round(mean_hp_before))
print(round(mean_hp_after))

249
249


In [80]:
selected = ['engine_hp', "engine_cylinders", "highway_mpg"]

In [97]:
df_Rolls = df[df['make'] == 'Rolls-Royce' ][selected]

In [98]:
X = df_Rolls.drop_duplicates()

In [99]:
X = X.values

In [100]:
X.T

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [101]:
XTX = X.T.dot(X)

XTX_inv = np.linalg.inv(XTX)
XTX_inv.sum()

0.032212320677486125

In [102]:
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [103]:
XTX_inv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [104]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]


In [105]:
w = XTX_inv.dot(X.T).dot(y)

In [106]:
w[0]

0.19989598183188978